
apiVersion: 1

datasources:
  - name: telegraf
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      token: ${INFLUXDB_PASSWORD}
    jsonData:
      version: Flux
      organization: admin
      defaultBucket: default 
      tlsSkipVerify: true
